name: <%= @project_name %>
configs:
  Enterprise Debug: debug
  AppStore Debug: debug
  Enterprise Release: release
  AppStore Release: release
options:
  bundleIdPrefix: com.<%= @project_name.camelcase(:lower) %>
targets:
  <%= @project_name %>-iOS:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: [Source]
    scheme:
      configVariants:
        - Enterprise
        - AppStore
    info:
      path: Source/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortraitUpsideDown]
        UILaunchStoryboardName: LaunchScreen
